name: instagram_feed
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
